[pytest]
pythonpath = .
asyncio_mode = auto
asyncio_default_test_loop_scope = session
testpaths = tests
python_files = test_*.py
addopts = -v --disable-warnings
env =
    ENV=TESTING
    CELERY_TASK_ALWAYS_EAGER=True