"""add_integrity_and_mastery

Revision ID: 4ef6b1a41817
Revises: 
Create Date: 2026-05-16 20:27:51.099864

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '4ef6b1a41817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Электронная почта (логин)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хеш пароля'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО пользователя'),
    sa.Column('role', sa.Enum('admin', 'teacher', 'ta', 'student', name='user_role'), nullable=False, comment='Роль пользователя в системе'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='ID организации или группы для изоляции данных'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активности аккаунта'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Флаг суперпользователя (доступ ко всем org_id)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('group',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_index(op.f('ix_group_org_id'), 'group', ['org_id'], unique=False)
    op.create_table('subject',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=False)
    op.create_index(op.f('ix_subject_org_id'), 'subject', ['org_id'], unique=False)
    op.create_table('group_students',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'student_id')
    )
    op.create_table('group_subjects',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'subject_id')
    )
    op.create_table('lecture',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'generating', 'review_required', 'published', 'archived', name='lecturestatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('open_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_id'), 'lecture', ['id'], unique=False)
    op.create_index(op.f('ix_lecture_org_id'), 'lecture', ['org_id'], unique=False)
    op.create_index(op.f('ix_lecture_subject_id'), 'lecture', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lecture_title'), 'lecture', ['title'], unique=False)
    op.create_table('chunk',
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_id'), 'chunk', ['id'], unique=False)
    op.create_index(op.f('ix_chunk_lecture_id'), 'chunk', ['lecture_id'], unique=False)
    op.create_table('examsession',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('current_draft', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('integrity_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examsession_id'), 'examsession', ['id'], unique=False)
    op.create_index(op.f('ix_examsession_lecture_id'), 'examsession', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_examsession_status'), 'examsession', ['status'], unique=False)
    op.create_index(op.f('ix_examsession_student_id'), 'examsession', ['student_id'], unique=False)
    op.create_table('question',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('key_theses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_chunk_id'), 'question', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_table('studentappeal',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='appeal_status'), nullable=False),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['session_id'], ['examsession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studentappeal_id'), 'studentappeal', ['id'], unique=False)
    op.create_index(op.f('ix_studentappeal_session_id'), 'studentappeal', ['session_id'], unique=False)
    op.create_index(op.f('ix_studentappeal_status'), 'studentappeal', ['status'], unique=False)
    op.create_index(op.f('ix_studentappeal_student_id'), 'studentappeal', ['student_id'], unique=False)
    op.create_table('studentanswer',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('formula_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_plagiarism', sa.Boolean(), nullable=False),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['examsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studentanswer_id'), 'studentanswer', ['id'], unique=False)
    op.create_index(op.f('ix_studentanswer_question_id'), 'studentanswer', ['question_id'], unique=False)
    op.create_index(op.f('ix_studentanswer_session_id'), 'studentanswer', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studentanswer_session_id'), table_name='studentanswer')
    op.drop_index(op.f('ix_studentanswer_question_id'), table_name='studentanswer')
    op.drop_index(op.f('ix_studentanswer_id'), table_name='studentanswer')
    op.drop_table('studentanswer')
    op.drop_index(op.f('ix_studentappeal_student_id'), table_name='studentappeal')
    op.drop_index(op.f('ix_studentappeal_status'), table_name='studentappeal')
    op.drop_index(op.f('ix_studentappeal_session_id'), table_name='studentappeal')
    op.drop_index(op.f('ix_studentappeal_id'), table_name='studentappeal')
    op.drop_table('studentappeal')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_index(op.f('ix_question_chunk_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_examsession_student_id'), table_name='examsession')
    op.drop_index(op.f('ix_examsession_status'), table_name='examsession')
    op.drop_index(op.f('ix_examsession_lecture_id'), table_name='examsession')
    op.drop_index(op.f('ix_examsession_id'), table_name='examsession')
    op.drop_table('examsession')
    op.drop_index(op.f('ix_chunk_lecture_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_lecture_title'), table_name='lecture')
    op.drop_index(op.f('ix_lecture_subject_id'), table_name='lecture')
    op.drop_index(op.f('ix_lecture_org_id'), table_name='lecture')
    op.drop_index(op.f('ix_lecture_id'), table_name='lecture')
    op.drop_table('lecture')
    op.drop_table('group_subjects')
    op.drop_table('group_students')
    op.drop_index(op.f('ix_subject_org_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_group_org_id'), table_name='group')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
